version: "3"

services:
  api-gateway:
    build: 
      context: .
      dockerfile: dockers/api-gateway/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: user
    volumes:
      - "./src/api-gateway:/app"
    command: 
      - npm run start:dev
    ports: 
      - 3000:3000
    networks:
      - ms-tut
    depends_on:
      - user-db

  user-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: user
    ports:
      - 3307:3306
    networks:
      - ms-tut

  catalog-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: catalog
    ports:
      - 3310:3306
    networks:
      - ms-tut

  catalog-php:
    build:
      context: .
      dockerfile: dockers/php/Dockerfile
    volumes:
      - "./src/catalog:/srv/app"
    ports:
      - "8388:80"
    depends_on:
      - catalog-db
      - redis
    environment:
      DB_DATABASE: catalog
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_HOST: catalog-db
      APP_URL: http://localhost:8388
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 1
    networks:
      - ms-tut

  basket-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: basket
    ports:
      - 3311:3306
    networks:
      - ms-tut

  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379
    networks:
      - ms-tut

  basket-php:
    build:
      context: .
      dockerfile: dockers/php/Dockerfile
    volumes:
      - "./src/basket:/srv/app"
    ports:
      - "8488:80"
    depends_on:
      - basket-db
      - redis
    environment:
      DB_DATABASE: basket
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_HOST: basket-db
      APP_URL: http://localhost:8488
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
    networks:
      - ms-tut

  basket-product-receiver:
    build:
      context: .
      dockerfile: dockers/python-receiver/Dockerfile
    environment:
      COLLECTION_URI: http://catalog-php/
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PS_CHANNEL: product_pubsub
      REDIS_CACHE_NAME: product
    volumes:
        - "./src/basket-product-receiver/src:/app"
    depends_on:
      - catalog-php
      - redis
    networks:
      - ms-tut

networks:
  ms-tut:
